# CONSTANTS THAT ARE USED FOR drawing/
# THEY DEFINE PLACEMENTS/COLORS AND DEFAULT FONTS/IMAGES PATHS


# SIZES
BACKGROUND_DIMENSIONS = (419, 404)
BLURRY_REGION_RADIUS = 12
BLURRY_REGION_SIZE = (395, 380)
BLACK_REGION_1_SIZE = (371, 118)
BLACK_REGION_2_SIZE = (371, 88)
BADGE_SIZE = (41, 41)
PFP_CIRCLE_SIZE = (100, 100)
XP_BAR_SIZE = (283, 10)


# OFFSETS
BLURRY_BACKGROUND_OFFSET = (12, 12)
BLACK_REGION_1_OFFSET = (24, 164)
BLACK_REGION_2_OFFSET = (24, 292)
FIRST_BADGE_OFFSET = (36, 329)
BADGES_SPACING = 10
PFP_CIRCLE_OFFSET = (295, 39)
XP_BAR_OFFSET = (100, 195)

# COLORS

# IMAGE PATHS
BADGES_MAP = {
    "operation_elysian_veteran": "badges/operation_elysian_vet.png",
    "daru69": "badges/daru69.png",
}

# FONTS
DEFAULT_FONT = "fonts/MerriweatherSansItalic/MerriweatherSans-VariableFont_wght.ttf"
